name: 'Grupo_F'
version: '1.0.0'
config-version: 2
profile: 'Analytics'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]
seed-paths: ["seeds"]
docs-paths: ["docs"]

target-path: "target"  
log-path: dbt_logs


packages-install-path: packages

clean-targets:        
    - "target"
    - "dbt_packages"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

macro-paths: ["custom_macros"]
query-comment: string

quoting:
  database: true | false
  schema: true | false
  identifier: true | false

models:
  <model-configs>

seeds:
  <seed-configs>

snapshots:
  <snapshot-configs>

sources:
  <source-configs>
  
tests:
  <test-configs>

vars:
  <variables>

on-run-start: sql-statement | [sql-statement]
on-run-end: sql-statement | [sql-statement]