with DADOS_COVID as (

select 
	_ROW NUMBER,
	RACA_COR,
	EVOLUCAO,
	CLASSIFICACAO_FINAL,
	SISTEMA,
	DT_INICIO_SINTOMAS,
	FAIXA_ETARIA,
	AP_RESIDENCIA_ESTADIA,
	DT_EVOLUCAO,
	DATA_ATUALIZACAO,
	DT_NOTIFIC,
	SEXO,
	BAIRRO_RESID_ESTADIA,
	_FIVETRAN_SYNCED,
	from PC_FIVETRAN_DB.GOOGLE_SHEETS.DADOS_COVID 
)

select * from DADOS_COVID